---
- hosts: localhost
  become: yes
  tasks:
  - name: install apache on centos
    yum: 
      name: httpd
      state: present
    when: ansible_os_family == "RedHat"
    tags:
      - install 
  - name: install apache on ubuntu server
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"
    tags: 
      - install
      - service
    
  - name: print free memory
    debug:
      msg: "free memory is {{ansible_memory_mb.real.free}}"
    tags:
      - debug 