---
- hosts: all
  tasks: 
  - name: find who is executing
    command: whoami
  - name: ping all
    command: 
  - name: findout current directory
    command: pwd
  - name: uninstall tree
    yum: 
      name: tree
      state: present
      